apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "payment-executor.fullname" . }}
  labels:
   {{- include "payment-executor.labels" . | nindent 4 }}
data:
  metrics_exporter: "none"
  otel_resource_attributes: "service.name=payment-executor"
  otel_otlp_endpoint: "{{ .Values.otel.endpoint }}"
  profile: "{{ .Values.profile }}"
